### PR TITLE
Revert "Introduce yourself to the world"

### PR DESCRIPTION
**Pull request by viswa0206**

### CODE REVIEW

**Comment by viswa0206** [comment]
[GitHub](http://github.com)

**Review by viswa0206 — COMMENTED** [review]
Good

**Review by viswa0206 — COMMENTED** [review]
Approve my pull request

**Review by Renita0612 — APPROVED** [review]

**Review by Renita0612 — APPROVED** [review]

**Comment by viswa0206** [comment]
https://github.com/viswa0206/markdown-portfolio.git

**Comment by viswa0206** [comment]
git://github.com/viswa0206/markdown-portfolio.git

**Pull request closed without merging**
